# Generated by Django 5.1.7 on 2025-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_dish_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="dish",
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes", to="kitchen.ingredient"
            ),
        ),
    ]
